[package]
name = "kurosawa_dia"
version = "1.4.0"
authors = ["Gabriel-Paulucci <gabrielpauluccimunizmendes@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "^0.10.5"
dotenv = "^0.15.0"
rand = "^0.8.3"
unic-emoji-char = "^0.9.0"
chrono = "^0.4.19"
unidecode = "^0.3.0"

[dependencies.tokio]
features = ["macros", "rt-multi-thread"]
version = "^1.5.0"